stages:
  prepare_data:
    cmd: python scripts/prepare_data.py
    deps:
      - scripts/prepare_data.py
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
      - data/processed/label_mapping.yaml
  
  train_models:
    cmd: python scripts/train_all_models.py
    deps:
      - scripts/train_all_models.py
      - data/processed/train.csv
    outs:
      - models/
    
  evaluate_models:
    cmd: python scripts/evaluate_all_models.py
    deps:
      - scripts/evaluate_all_models.py
      - data/processed/test.csv
      - models/
    outs:
      - reports/